<?php

declare(strict_types=1);

namespace App\Bundle\LeoTelegramSdk\ValueObject;

use ArrayObject;

class PhotoCollection extends ArrayObject
{
    public function __construct($array = [], $flags = 0, $iteratorClass = "ArrayIterator")
    {
        assert(empty($array));

        parent::__construct($array, $flags, $iteratorClass);
    }

    public function append($value)
    {
        assert($value instanceof Photo);

        parent::append($value); // TODO: Change the autogenerated stub
    }

    public function offsetSet($key, $value)
    {
        assert($value instanceof Photo);

        parent::offsetSet($key, $value); // TODO: Change the autogenerated stub
    }
}
