parameters:
    default_enable: false
    telegram_bot_secure_token: '%env(TELEGRAM_BOT_SECURE_TOKEN)%'

    api:
        telegram_bot:
            enable: '%env(default:default_enable:TELEGRAM_BOT_ENABLE)%'
            test_chat_ids: '341667531'
            connection:
                telegram: 'https://api.telegram.org/bot%env(TELEGRAM_BOT_KEY)%'
                telegram_files: 'https://api.telegram.org/file/bot%env(TELEGRAM_BOT_KEY)%'
                self_host: '%env(SELF_HOST)%'
            endpoint:
                webhook_register:
                    connection: 'telegram'
                    method: 'GET'
                    path: '/setwebhook'
                    fields:
                        url:
                            name: 'url'
                            type: 'string'
                            default: '{api|telegram_bot|connection|self_host}/telegram/sdk/bot/entrypoint'
                get_file_info:
                    connection: 'telegram'
                    method: 'GET'
                    path: '/getFile'
                download_file:
                    connection: 'telegram_files'
                    method: 'GET'
                    path: '/'
                send_message:
                    connection: 'telegram'
                    method: 'GET'
                    path: '/sendMessage'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

imports:
    - { resource: '../src/Bundle/LeoTelegramSdk/Resources/config/packages/messenger.yaml' }